-- CB/CAA/CSG の基本権限と表領域クォータを付与
-- ORA-01950(no privileges on tablespace USERS) 対策
-- ORA-01045(user lacks CREATE SESSION privilege) 対策

ALTER USER CB DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER CAA DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER CSG DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

ALTER USER CB QUOTA UNLIMITED ON USERS;
ALTER USER CAA QUOTA UNLIMITED ON USERS;
ALTER USER CSG QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO CB;
GRANT CREATE SESSION TO CAA;
GRANT CREATE SESSION TO CSG;