CREATE TABLE CSG.CSG03
(
    FILESEQ                        NUMBER(12,0) NOT NULL,
    FILENM                         VARCHAR2(255) NOT NULL,
    DELFLG                         VARCHAR2(1) DEFAULT 0 NOT NULL,
    DYSET                          VARCHAR2(14),
    DYUPD                          VARCHAR2(14),
    USRSET                         VARCHAR2(10),
    USRUPD                         VARCHAR2(10),
    PRGUPD                         VARCHAR2(10),
    CONSTRAINT CSG03_PRIMARY PRIMARY KEY (FILESEQ) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
COMMENT ON TABLE CSG.CSG03 IS 'ファイル管理'
/
COMMENT ON COLUMN CSG.CSG03.FILESEQ IS 'ファイル管理番号'
/
COMMENT ON COLUMN CSG.CSG03.FILENM IS 'ファイル名'
/
COMMENT ON COLUMN CSG.CSG03.DELFLG IS '削除フラグ(削除:9)'
/
COMMENT ON COLUMN CSG.CSG03.DYSET IS '登録日時'
/
COMMENT ON COLUMN CSG.CSG03.DYUPD IS '更新日時'
/
COMMENT ON COLUMN CSG.CSG03.USRSET IS '登録ユーザーID'
/
COMMENT ON COLUMN CSG.CSG03.USRUPD IS '更新ユーザーID'
/
COMMENT ON COLUMN CSG.CSG03.PRGUPD IS '更新プログラムID'
/
