CREATE TABLE CSG.CSG04
(
    BUSYONO                        VARCHAR2(5) NOT NULL,
    CRTMETHOD                      NUMBER(1,0) NOT NULL,
    DYEXE                          VARCHAR2(4),
    DYSET                          VARCHAR2(14),
    DYUPD                          VARCHAR2(14),
    USRSET                         VARCHAR2(10),
    USRUPD                         VARCHAR2(10),
    PRGUPD                         VARCHAR2(10),
    CONSTRAINT SYS_C0011874 PRIMARY KEY (BUSYONO) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
COMMENT ON TABLE CSG.CSG04 IS '来期スキル設定'
/
COMMENT ON COLUMN CSG.CSG04.BUSYONO IS '拠点/部署No'
/
COMMENT ON COLUMN CSG.CSG04.CRTMETHOD IS '実施方法'
/
COMMENT ON COLUMN CSG.CSG04.DYEXE IS 'リセット日付'
/
COMMENT ON COLUMN CSG.CSG04.DYSET IS '登録日時'
/
COMMENT ON COLUMN CSG.CSG04.DYUPD IS '更新日時'
/
COMMENT ON COLUMN CSG.CSG04.USRSET IS '登録ユーザーID'
/
COMMENT ON COLUMN CSG.CSG04.USRUPD IS '更新ユーザーID'
/
COMMENT ON COLUMN CSG.CSG04.PRGUPD IS '更新プログラムID'
/
