CREATE TABLE CSG.CSGM24
(
    SKL_CD                         NUMBER(12,0) NOT NULL,
    MANUALSEQ                      NUMBER(12,0) NOT NULL,
    LANG                           VARCHAR2(2) NOT NULL,
    DYSET                          VARCHAR2(14),
    DYUPD                          VARCHAR2(14),
    USRSET                         VARCHAR2(10),
    USRUPD                         VARCHAR2(10),
    PRGUPD                         VARCHAR2(10),
    MANUALNM                       VARCHAR2(255) NOT NULL,
    MANUALURL                      VARCHAR2(1000) NOT NULL,
    CONSTRAINT CSGM24_PRIMARY PRIMARY KEY (SKL_CD,MANUALSEQ) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE,
    CONSTRAINT CSGM24_CHKLANG CHECK (LANG IN ('ja','en','zh','zw'))
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
COMMENT ON TABLE CSG.CSGM24 IS 'マニュアルマスタ'
/
COMMENT ON COLUMN CSG.CSGM24.SKL_CD IS 'スキルコード'
/
COMMENT ON COLUMN CSG.CSGM24.MANUALSEQ IS 'ファイル管理番号'
/
COMMENT ON COLUMN CSG.CSGM24.LANG IS '言語(日本語:ja 英語:en 簡体:zh 繁体:zw)'
/
COMMENT ON COLUMN CSG.CSGM24.DYSET IS '登録日時'
/
COMMENT ON COLUMN CSG.CSGM24.DYUPD IS '更新日時'
/
COMMENT ON COLUMN CSG.CSGM24.USRSET IS '登録ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM24.USRUPD IS '更新ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM24.PRGUPD IS '更新プログラムID'
/
COMMENT ON COLUMN CSG.CSGM24.MANUALNM IS '名称'
/
COMMENT ON COLUMN CSG.CSGM24.MANUALURL IS 'URL'
/
