CREATE TABLE CSG.CSGM23
(
    SKL_CD                         NUMBER(12,0) NOT NULL,
    BUSYONO                        NUMBER(5,0) NOT NULL,
    DYSET                          VARCHAR2(14),
    DYUPD                          VARCHAR2(14),
    USRSET                         VARCHAR2(10),
    USRUPD                         VARCHAR2(10),
    PRGUPD                         VARCHAR2(10),
    CONSTRAINT CSGM23_PRIMARY PRIMARY KEY (SKL_CD,BUSYONO) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
COMMENT ON TABLE CSG.CSGM23 IS 'スキル対象拠点部署マスタ'
/
COMMENT ON COLUMN CSG.CSGM23.SKL_CD IS 'スキルコード'
/
COMMENT ON COLUMN CSG.CSGM23.BUSYONO IS '拠点/部署No'
/
COMMENT ON COLUMN CSG.CSGM23.DYSET IS '登録日時'
/
COMMENT ON COLUMN CSG.CSGM23.DYUPD IS '更新日時'
/
COMMENT ON COLUMN CSG.CSGM23.USRSET IS '登録ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM23.USRUPD IS '更新ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM23.PRGUPD IS '更新プログラムID'
/
