CREATE TABLE CSG.CSGM03
(
    EVALSEQ                        NUMBER(12,0) NOT NULL,
    SYAIN                          VARCHAR2(10) NOT NULL,
    BUSYONO                        NUMBER(5,0) NOT NULL,
    ODR                            NUMBER(3,0) DEFAULT 0,
    DYSET                          VARCHAR2(14),
    DYUPD                          VARCHAR2(14),
    USRSET                         VARCHAR2(10),
    USRUPD                         VARCHAR2(10),
    PRGUPD                         VARCHAR2(10),
    CONSTRAINT CSGM03_PRIMARY PRIMARY KEY (EVALSEQ) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE,
    CONSTRAINT CSGM03_UNIQUE UNIQUE (SYAIN, BUSYONO) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
COMMENT ON TABLE CSG.CSGM03 IS '評価者マスタ'
/
COMMENT ON COLUMN CSG.CSGM03.EVALSEQ IS '評価者管理番号'
/
COMMENT ON COLUMN CSG.CSGM03.SYAIN IS '評価者社員番号'
/
COMMENT ON COLUMN CSG.CSGM03.BUSYONO IS '評価対象拠点/部署No'
/
COMMENT ON COLUMN CSG.CSGM03.ODR IS '表示順'
/
COMMENT ON COLUMN CSG.CSGM03.DYSET IS '登録日時'
/
COMMENT ON COLUMN CSG.CSGM03.DYUPD IS '更新日時'
/
COMMENT ON COLUMN CSG.CSGM03.USRSET IS '登録ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM03.USRUPD IS '更新ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM03.PRGUPD IS '更新プログラムID'
/
