CREATE TABLE CSG.CSGM25
(
    MDL_CD                         NUMBER(12,0) NOT NULL,
    LC_CD                          NUMBER(12,0) NOT NULL,
    DYSET                          VARCHAR2(14),
    DYUPD                          VARCHAR2(14),
    USRSET                         VARCHAR2(10),
    USRUPD                         VARCHAR2(10),
    PRGUPD                         VARCHAR2(10),
    CONSTRAINT CSGM25_UK PRIMARY KEY (MDL_CD,LC_CD) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
        ENABLE
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
COMMENT ON TABLE CSG.CSGM25 IS 'LC'
/
COMMENT ON COLUMN CSG.CSGM25.MDL_CD IS '機種コード'
/
COMMENT ON COLUMN CSG.CSGM25.LC_CD IS 'LCコード'
/
COMMENT ON COLUMN CSG.CSGM25.DYSET IS '登録日時'
/
COMMENT ON COLUMN CSG.CSGM25.DYUPD IS '更新日時'
/
COMMENT ON COLUMN CSG.CSGM25.USRSET IS '登録ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM25.USRUPD IS '更新ユーザーID'
/
COMMENT ON COLUMN CSG.CSGM25.PRGUPD IS '更新プログラムID'
/
